//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSAPI_Manage {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class QRS_Manage : global::System.Configuration.ApplicationSettingsBase {
        
        private static QRS_Manage defaultInstance = ((QRS_Manage)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new QRS_Manage())));
        
        public static QRS_Manage Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string serverUrl {
            get {
                return ((string)(this["serverUrl"]));
            }
            set {
                this["serverUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string serverHeaderName {
            get {
                return ((string)(this["serverHeaderName"]));
            }
            set {
                this["serverHeaderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string serverHeaderValue {
            get {
                return ((string)(this["serverHeaderValue"]));
            }
            set {
                this["serverHeaderValue"] = value;
            }
        }
    }
}
